<?php
/**
 * FAQ Group CPT Class
 *
 * @package Website_FAQ_Maker
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * FAQ Group CPT Class
 */
class WFM_FAQ_CPT {

	/**
	 * Constructor.
	 */
	public function __construct() {
		add_action( 'init', array( $this, 'register_cpt' ) );
		add_action( 'add_meta_boxes', array( $this, 'add_meta_boxes' ) );
		add_action( 'save_post', array( $this, 'save_meta_box_data' ) );
	}

	/**
	 * Register the Custom Post Type.
	 */
	public function register_cpt() {
		$labels = array(
			'name'                  => _x( 'FAQ Groups', 'Post Type General Name', 'website-faq-maker' ),
			'singular_name'         => _x( 'FAQ Group', 'Post Type Singular Name', 'website-faq-maker' ),
			'menu_name'             => __( 'FAQ Generator', 'website-faq-maker' ),
			'name_admin_bar'        => __( 'FAQ Group', 'website-faq-maker' ),
			'archives'              => __( 'FAQ Group Archives', 'website-faq-maker' ),
			'attributes'            => __( 'FAQ Group Attributes', 'website-faq-maker' ),
			'parent_item_colon'     => __( 'Parent FAQ Group:', 'website-faq-maker' ),
			'all_items'             => __( 'All FAQ Groups', 'website-faq-maker' ),
			'add_new_item'          => __( 'Add New FAQ Group', 'website-faq-maker' ),
			'add_new'               => __( 'Add New', 'website-faq-maker' ),
			'new_item'              => __( 'New FAQ Group', 'website-faq-maker' ),
			'edit_item'             => __( 'Edit FAQ Group', 'website-faq-maker' ),
			'update_item'           => __( 'Update FAQ Group', 'website-faq-maker' ),
			'view_item'             => __( 'View FAQ Group', 'website-faq-maker' ),
			'view_items'            => __( 'View FAQ Groups', 'website-faq-maker' ),
			'search_items'          => __( 'Search FAQ Group', 'website-faq-maker' ),
			'not_found'             => __( 'Not found', 'website-faq-maker' ),
			'not_found_in_trash'    => __( 'Not found in Trash', 'website-faq-maker' ),
			'featured_image'        => __( 'Featured Image', 'website-faq-maker' ),
			'set_featured_image'    => __( 'Set featured image', 'website-faq-maker' ),
			'remove_featured_image' => __( 'Remove featured image', 'website-faq-maker' ),
			'use_featured_image'    => __( 'Use as featured image', 'website-faq-maker' ),
			'insert_into_item'      => __( 'Insert into FAQ Group', 'website-faq-maker' ),
			'uploaded_to_this_item' => __( 'Uploaded to this FAQ Group', 'website-faq-maker' ),
			'items_list'            => __( 'FAQ Groups list', 'website-faq-maker' ),
			'items_list_navigation' => __( 'FAQ Groups list navigation', 'website-faq-maker' ),
			'filter_items_list'     => __( 'Filter FAQ Groups list', 'website-faq-maker' ),
		);
		$args   = array(
			'label'               => __( 'FAQ Group', 'website-faq-maker' ),
			'description'         => __( 'Groups of FAQs generated by AI', 'website-faq-maker' ),
			'labels'              => $labels,
			'supports'            => array( 'title' ), // We only need title, content is stored in meta
			'hierarchical'        => false,
			'public'              => false, // Not public, only via shortcode
			'show_ui'             => true,
			'show_in_menu'        => true,
			'menu_position'       => 20,
			'menu_icon'           => 'dashicons-format-chat',
			'show_in_admin_bar'   => true,
			'show_in_nav_menus'   => false,
			'can_export'          => true,
			'has_archive'         => false,
			'exclude_from_search' => true,
			'publicly_queryable'  => false,
			'capability_type'     => 'post',
			'show_in_rest'        => false, // No Gutenberg for now, keep it simple
		);
		register_post_type( 'faq_group', $args );
	}

	/**
	 * Add Meta Boxes.
	 */
	public function add_meta_boxes() {
		add_meta_box(
			'wfm_faq_data_box',
			__( 'FAQ Data', 'website-faq-maker' ),
			array( $this, 'render_faq_data_box' ),
			'faq_group',
			'normal',
			'high'
		);

		add_meta_box(
			'wfm_faq_shortcode_box',
			__( 'Shortcode', 'website-faq-maker' ),
			array( $this, 'render_shortcode_box' ),
			'faq_group',
			'side',
			'high'
		);
	}

	/**
	 * Render FAQ Data Meta Box.
	 *
	 * @param WP_Post $post The post object.
	 */
	public function render_faq_data_box( $post ) {
		// Add an nonce field so we can check for it later.
		wp_nonce_field( 'wfm_save_faq_data', 'wfm_faq_data_nonce' );

		$faqs = get_post_meta( $post->ID, '_wfm_faqs', true );
		if ( ! is_array( $faqs ) ) {
			$faqs = array();
		}

		echo '<div id="wfm-faq-list">';
		if ( empty( $faqs ) ) {
			echo '<p>' . esc_html__( 'No FAQs generated yet.', 'website-faq-maker' ) . '</p>';
		} else {
			foreach ( $faqs as $index => $faq ) {
				$question = isset( $faq['question'] ) ? $faq['question'] : '';
				$answer   = isset( $faq['answer'] ) ? $faq['answer'] : '';
				?>
				<div class="wfm-faq-item" style="margin-bottom: 15px; border: 1px solid #ddd; padding: 10px; background: #fff;">
					<p>
						<label><strong><?php esc_html_e( 'Question:', 'website-faq-maker' ); ?></strong></label><br>
						<input type="text" name="wfm_faqs[<?php echo esc_attr( $index ); ?>][question]" value="<?php echo esc_attr( $question ); ?>" style="width: 100%;">
					</p>
					<p>
						<label><strong><?php esc_html_e( 'Answer:', 'website-faq-maker' ); ?></strong></label><br>
						<textarea name="wfm_faqs[<?php echo esc_attr( $index ); ?>][answer]" style="width: 100%;" rows="3"><?php echo esc_textarea( $answer ); ?></textarea>
					</p>
					<button type="button" class="button wfm-remove-faq" onclick="this.parentNode.remove()"><?php esc_html_e( 'Remove', 'website-faq-maker' ); ?></button>
				</div>
				<?php
			}
		}
		echo '</div>';
		
		// Hidden template for new items if we want to add manually later, but for now just generated ones.
		// We can add a "Add Manual FAQ" button later if needed.
	}

	/**
	 * Render Shortcode Meta Box.
	 *
	 * @param WP_Post $post The post object.
	 */
	public function render_shortcode_box( $post ) {
		echo '<p>' . esc_html__( 'Copy this shortcode to display the FAQs:', 'website-faq-maker' ) . '</p>';
		echo '<code>[faq_group id="' . esc_attr( $post->ID ) . '"]</code>';
	}

	/**
	 * Save Meta Box Data.
	 *
	 * @param int $post_id The post ID.
	 */
	public function save_meta_box_data( $post_id ) {
		// Check if our nonce is set.
		if ( ! isset( $_POST['wfm_faq_data_nonce'] ) ) {
			return;
		}

		// Verify that the nonce is valid.
		if ( ! wp_verify_nonce( $_POST['wfm_faq_data_nonce'], 'wfm_save_faq_data' ) ) {
			return;
		}

		// If this is an autosave, our form has not been submitted, so we don't want to do anything.
		if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
			return;
		}

		// Check the user's permissions.
		if ( isset( $_POST['post_type'] ) && 'faq_group' === $_POST['post_type'] ) {
			if ( ! current_user_can( 'edit_post', $post_id ) ) {
				return;
			}
		}

		/* OK, it's safe for us to save the data now. */

		// Make sure that it is set.
		if ( ! isset( $_POST['wfm_faqs'] ) ) {
			// If not set (e.g. all removed), save empty array
			update_post_meta( $post_id, '_wfm_faqs', array() );
			return;
		}

		// Sanitize user input.
		$faqs_data = $_POST['wfm_faqs'];
		$sanitized_faqs = array();

		if ( is_array( $faqs_data ) ) {
			foreach ( $faqs_data as $faq ) {
				if ( isset( $faq['question'] ) && isset( $faq['answer'] ) ) {
					$sanitized_faqs[] = array(
						'question' => sanitize_text_field( $faq['question'] ),
						'answer'   => sanitize_textarea_field( $faq['answer'] ), // Allow some HTML? For now strict.
					);
				}
			}
		}

		// Update the meta field in the database.
		update_post_meta( $post_id, '_wfm_faqs', $sanitized_faqs );
	}
}
